name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  CI: true
  MONGO_DB_URI: mongodb://localhost:27017/project-manager
  SHOW_MONGO: NO
  TOKEN_SECRET: faeifnefneongegnedgbrngedgdnkjvxbvduibrsgbbgkbegbgnelgnrengengnrgbe
  PORT: 3000

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        mongodb-version: ['4.2', '4.4', '5.0']

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - run: npm ci
      - run: npm run test
      - name: Add remote origin
        run: |
          git remote add heroku https://heroku:${{ secrets.API_KEY }}@git.heroku.com/${{ secrets.APP_NAME }}.git
      - name: Deploy to Heroku
        run: |
          git push heroku HEAD:main -f
